<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmartDelivery.Application\SmartDelivery.Application.csproj" />
    <ProjectReference Include="..\SmartDelivery.Infrastructure\SmartDelivery.Infrastructure.csproj" />
    <ProjectReference Include="..\SmartDelivery.Persistence\SmartDelivery.Persistence.csproj" />
  </ItemGroup>

</Project>
